#define NODE_SZ 25.0f
#define NODE_BORDER 5.0f
#define HIDE_TXT_SCALE 0.6f
#define HIDE_CONTENT_SCALE 0.9f
#define HIDE_ARROW_SCALE 0.4f
#define EDGE_TXT_SPACING 4.0f
#define EDGE_TXT_OFFSET 1.0f
#define FONT_SZ 32
#define EDGE_FONT_COEFF 1.0f
#define HIGHLIGHT_INTENSITY 0.5f
#define HIGHLIGHT_INTENSITY_2 1.0f
#define ARROW_SZ 0.04f

#define EDGE_THICK 5.0f
#define EDGE_HOVER_R 4.0f
#define SPRING_LEN 100.0f
#define SPRING_STR 0.05f
#define LINKS_DENSITY 3.0f